export  { default as Home} from './Home/Home'
export {default as ShoppingCat} from './ShoppingCat/ShoppingCat'
export {default as ProductView} from './ProductView/ProductView'
export {default as Register} from './Register/Register'
export {default as Login} from './Login/Login'
export {default as Cart} from './Cart/Cart'